# Site settings
title: Saimani Ippili - Portfolio
description: A collection of my projects and achievements
baseurl: "" # Leave empty since it’s hosted at saimaniippili.github.io
url: "https://saimaniippili.github.io" # Your GitHub Pages URL
email: saimani@example.com # Replace with your actual email

# Owner/Author info
author:
  name: Saimani Ippili
  email: saimani@example.com # Replace with your actual email
  bio: "Creative developer passionate about building innovative solutions." # Customize this!
  avatar: "/assets/images/profile-pic.jpg" # Add a profile pic to /assets/images/ later
  twitter: Smippili
  github: saimaniippili
  linkedin: saimani-ippili-356830247

# Theme settings
remote_theme: mmistakes/minimal-mistakes@4.24.0 # Minimal Mistakes theme
minimal_mistakes_skin: "mint" # A fresh, modern look - you can change to "default", "air", etc.

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-seo-tag

# Collections for portfolio projects
collections:
  projects:
    output: true
    permalink: /projects/:title/

# Default settings for project pages
defaults:
  - scope:
      path: ""
      type: projects
    values:
      layout: single
      author_profile: true
      read_time: true
      share: true
      related: true

# Social sharing and footer links
footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://x.com/Smippili"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/saimaniippili"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/saimani-ippili-356830247/"
